import { FactCollection } from '../../types';

export const deceptionManipulation: FactCollection = {
  id: 'deception-manipulation',
  categoryId: 'crime',
  title: 'Deception & Manipulation',
  description: 'How lies are told, and how predatory patterns operate.',
  icon: 'fingerprint',
  colorClass: 'text-zinc-400',
  facts: [
    {
      id: 'dec-1',
      collectionId: 'deception-manipulation',
      number: 1,
      title: 'People are barely better than chance at detecting lies.',
      readingTimeMinutes: 4,
      evidenceLevel: 5,
      summary: 'A large meta-analysis found that, on average, people correctly identify lies and truths only about 54% of the time — close to coin-flipping.',
      whyItHappens: 'There is no reliable single “tell”. The cues people rely on — nervousness, eye contact — are weak, and confidence in one’s own judgment is often misplaced.',
      realWorldExample: 'Studies of police interrogators and judges find accuracy barely above chance, despite high confidence.',
      practicalUse: 'Trust evidence and consistency across time over gut feeling, and look for clusters of cues rather than any single sign.',
      relatedConcepts: ['Deception detection', 'Othello error', 'Cluster principle'],
      references: [
        { title: 'Accuracy of deception judgments', source: 'Personality and Social Psychology Review', year: 2006 },
      ],
      dateAdded: '2024-05-01',
    },
    {
      id: 'dec-2',
      collectionId: 'deception-manipulation',
      number: 2,
      title: 'Some personality patterns are built around exploitation.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'The “dark triad” — narcissism, Machiavellianism and psychopathy — describes traits linked to manipulation, low empathy and a willingness to exploit others.',
      whyItHappens: 'These traits appear to combine callousness with strategic social skill, which can confer short-term advantage in competitive settings.',
      realWorldExample: 'Charming, confident and quick to charm a new target, then dismissive once the target is committed — a recurring description in accounts of exploitative relationships.',
      practicalUse: 'Watch patterns over time — especially how someone treats people who can offer them nothing — rather than relying on first impressions.',
      relatedConcepts: ['Dark triad', 'Machiavellianism', 'Psychopathy'],
      references: [
        { title: 'The Dark Triad of personality', source: 'Journal of Research in Personality', year: 2002 },
      ],
      dateAdded: '2024-05-02',
    },
    {
      id: 'dec-3',
      collectionId: 'deception-manipulation',
      number: 3,
      title: 'Gaslighting is a pattern, not a single lie.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'Gaslighting is a sustained effort to make someone doubt their own memory, perception and sanity, through denial, contradiction and trivialising.',
      whyItHappens: 'Repeatedly undermining a person’s grip on reality shifts power: the victim becomes dependent on the manipulator to define what is true.',
      realWorldExample: '“That never happened. You’re remembering it wrong again.” — repeated often enough, the target begins to distrust their own recall.',
      practicalUse: 'Keep records of events and conversations, and check reality with trusted people outside the relationship.',
      relatedConcepts: ['Gaslighting', 'Coercive control', 'DARVO'],
      references: [
        { title: 'Gaslighting: A clinical review', source: 'Journal of Emotional Abuse', year: 2007 },
      ],
      dateAdded: '2024-05-03',
    },
    {
      id: 'dec-4',
      collectionId: 'deception-manipulation',
      number: 4,
      title: 'Predatory trust is built slowly and deliberately.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'Grooming is a gradual process of building trust, isolating the target and testing boundaries before escalating to abuse or exploitation.',
      whyItHappens: 'By pacing the approach, the manipulator lowers the target’s defences and normalises early boundary crossings, so later harm meets less resistance.',
      realWorldExample: 'A mentor who over-shares, engineers private access, and slowly erodes boundaries — each step small enough to be dismissed alone.',
      practicalUse: 'Notice when access is being engineered — isolation, secrets, “you’re so mature for your age” — and keep trusted people in the loop.',
      relatedConcepts: ['Grooming', 'Isolation tactics', 'Boundary testing'],
      references: [
        { title: 'The grooming process in child sexual abuse', source: 'Journal of Child Sexual Abuse', year: 2016 },
      ],
      dateAdded: '2024-05-04',
    },
    {
      id: 'dec-5',
      collectionId: 'deception-manipulation',
      number: 5,
      title: 'Abusers often reverse the roles of victim and offender.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'DARVO — Deny, Attack, Reverse Victim and Offender — describes how a person accused of wrongdoing deflects blame by casting themselves as the true victim.',
      whyItHappens: 'Flipping the roles redirects scrutiny, exhausts the actual victim, and recruits bystanders to the offender’s side.',
      realWorldExample: 'Confronted about harm, the person denies it, attacks the accuser’s motives, and claims to be the one being persecuted.',
      practicalUse: 'Keep the focus on the specific behaviour, resist being pulled into defending your own credibility, and seek outside corroboration.',
      relatedConcepts: ['DARVO', 'Blame shifting', 'Smear campaign'],
      references: [
        { title: 'DARVO: Deny, Attack, Reverse Victim and Offender', source: 'Journal of Aggression, Maltreatment & Trauma', year: 2017 },
      ],
      dateAdded: '2024-05-05',
    },
  ],
};
