import { FactCollection } from '../../types';

export const attachmentAttraction: FactCollection = {
  id: 'attachment-attraction',
  categoryId: 'relationships',
  title: 'Attachment & Attraction',
  description: 'Why we bond, who we are drawn to, and how early patterns follow us.',
  icon: 'heart-pulse',
  colorClass: 'text-rose-500',
  facts: [
    {
      id: 'attach-1',
      collectionId: 'attachment-attraction',
      number: 1,
      title: 'The way you bonded as a child tends to show up in adult relationships.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'Adult attachment styles — secure, anxious and avoidant — predict how people behave in close relationships, especially under stress or conflict.',
      whyItHappens: 'Early caregiving shapes internal “working models” of whether others are reliable and whether the self is worthy of care. Those models guide expectations and behaviour long after childhood.',
      realWorldExample: 'An anxiously attached partner may seek constant reassurance, while an avoidant partner may withdraw precisely when closeness increases.',
      practicalUse: 'Recognising your default pattern — and your partner’s — turns reactive behaviour into something you can name and work with rather than fight about.',
      relatedConcepts: ['Attachment styles', 'Working models', 'Emotional availability'],
      references: [
        { title: 'Romantic love conceptualized as an attachment process', source: 'Journal of Personality and Social Psychology', year: 1987 },
      ],
      dateAdded: '2024-03-01',
    },
    {
      id: 'attach-2',
      collectionId: 'attachment-attraction',
      number: 2,
      title: 'We grow to like people simply because we see them often.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'The mere exposure effect is the tendency to develop a preference for things — and people — merely because we have been exposed to them repeatedly.',
      whyItHappens: 'Repeated, safe exposure reduces the sense of threat and increases processing fluency, which the mind misreads as liking.',
      realWorldExample: 'In one study, students who attended a class more often were rated more likeable by their peers, with no other interaction needed.',
      practicalUse: 'Consistent, low-pressure presence — showing up again and again — builds familiarity and trust far better than a single intense encounter.',
      relatedConcepts: ['Mere exposure effect', 'Familiarity', 'Proximity'],
      references: [
        { title: 'Exposure effects in a field setting', source: 'Journal of Experimental Social Psychology', year: 1992 },
      ],
      dateAdded: '2024-03-02',
    },
    {
      id: 'attach-3',
      collectionId: 'attachment-attraction',
      number: 3,
      title: 'Gradually escalating self-disclosure creates closeness fast.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'Structured, escalating personal disclosure — the “36 questions” — reliably increases feelings of closeness between two people.',
      whyItHappens: 'Reciprocal vulnerability signals trust and builds interdependence. Each side’s openness invites matching openness, deepening the bond.',
      realWorldExample: 'In the original experiment, participants who exchanged increasingly personal answers reported feeling significantly closer to a stranger within about 45 minutes.',
      practicalUse: 'To deepen a relationship, move from small talk to genuine disclosure in steps — and respond to openness with openness of your own.',
      relatedConcepts: ['Self-disclosure', 'Vulnerability', 'Reciprocity'],
      references: [
        { title: 'The Experimental Generation of Interpersonal Closeness', source: 'Personality and Social Psychology Bulletin', year: 1997 },
      ],
      dateAdded: '2024-03-03',
    },
    {
      id: 'attach-4',
      collectionId: 'attachment-attraction',
      number: 4,
      title: 'A handful of behaviours predict which relationships will end.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'Gottman identified four communication patterns — criticism, contempt, defensiveness and stonewalling, the “Four Horsemen” — that strongly predict relationship breakdown.',
      whyItHappens: 'These patterns attack a partner’s character rather than a specific problem, escalating conflict and eroding the sense of being on the same team.',
      realWorldExample: '“You always forget things” (criticism) lands very differently from “I felt let down when the plan slipped” (a specific complaint).',
      practicalUse: 'Replace criticism with a specific complaint, defensiveness with taking some responsibility, and stonewalling with a short, agreed break before returning to the conversation.',
      relatedConcepts: ['Four Horsemen', 'Contempt', 'Conflict resolution'],
      references: [
        { title: 'Marital processes predictive of later dissolution', source: 'Journal of Personality and Social Psychology', year: 1992 },
      ],
      dateAdded: '2024-03-04',
    },
  ],
};

export const communicationConflict: FactCollection = {
  id: 'communication-conflict',
  categoryId: 'relationships',
  title: 'Communication & Conflict',
  description: 'How small choices in how we talk decide how relationships go.',
  icon: 'git-branch',
  colorClass: 'text-purple-500',
  facts: [
    {
      id: 'comm-1',
      collectionId: 'communication-conflict',
      number: 1,
      title: 'How you respond to good news matters as much as how you respond to bad.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Active constructive responding — engaging enthusiastically with a partner’s good news — is strongly linked to higher relationship quality and stability.',
      whyItHappens: 'Celebrating good news builds capital of felt support. Passive or dismissive responses quietly signal that a partner’s joy does not matter.',
      realWorldExample: 'A partner shares a promotion. Enthusiastic questions deepen the bond; a distracted “That’s nice” punctures it.',
      practicalUse: 'When someone you care about shares good news, stop and engage with it specifically and warmly — do not just acknowledge it.',
      relatedConcepts: ['Active constructive responding', 'Emotional validation', 'Support'],
      references: [
        { title: 'What do you do when things go right?', source: 'Journal of Personality and Social Psychology', year: 2004 },
      ],
      dateAdded: '2024-03-05',
    },
    {
      id: 'comm-2',
      collectionId: 'communication-conflict',
      number: 2,
      title: 'Criticise the behaviour, not the person.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Complaints target a specific behaviour and can be acted on; criticism attacks character and provokes defence.',
      whyItHappens: 'Character attacks trigger threat responses and self-protection, which shut down problem-solving and escalate the conflict.',
      realWorldExample: '“I feel overwhelmed when the chores pile up” invites change. “You’re so lazy” invites a fight.',
      practicalUse: 'Use the formula: I feel ___ about ___ because ___. Keep the focus on the situation, not the person’s identity.',
      relatedConcepts: ['Criticism vs. complaint', 'Nonviolent communication', 'I-statements'],
      references: [
        { title: 'The Seven Principles for Making Marriage Work', source: 'Crown', year: 1999 },
      ],
      dateAdded: '2024-03-06',
    },
    {
      id: 'comm-3',
      collectionId: 'communication-conflict',
      number: 3,
      title: 'Tiny repair attempts decide how arguments end.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Repair attempts — a small joke, a softening, an apology, a touch — de-escalate conflict and, when accepted, keep arguments from spiralling.',
      whyItHappens: 'Conflict escalates through mutual reactivity. A repair attempt interrupts the cycle and signals that the relationship matters more than winning.',
      realWorldExample: 'Mid-argument, one partner says “Can we take a breath?” and the other accepts — the temperature drops.',
      practicalUse: 'Learn to send and receive repairs: notice the small gestures that ease tension and respond to them rather than pushing on.',
      relatedConcepts: ['Repair attempts', 'De-escalation', 'Conflict resolution'],
      references: [
        { title: 'The relationship between repair attempts and conflict outcomes', source: 'Gottman Institute research', year: 1994 },
      ],
      dateAdded: '2024-03-07',
    },
  ],
};
