import { FactCollection } from '../../types';

export const socialInfluence: FactCollection = {
  id: 'social-influence',
  categoryId: 'social',
  title: 'Social Influence',
  description: 'How groups, authority and the presence of others change what we do.',
  icon: 'network',
  colorClass: 'text-emerald-500',
  facts: [
    {
      id: 'soc-1',
      collectionId: 'social-influence',
      number: 1,
      title: 'The more people present, the less likely any one of them helps.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'The bystander effect is the finding that individuals are less likely to help a victim when other people are present.',
      whyItHappens: 'Responsibility diffuses across the group, and the calm of others is read as evidence that nothing is wrong (pluralistic ignorance).',
      realWorldExample: 'In an emergency with many onlookers, each person assumes someone else will act — so often no one does.',
      practicalUse: 'If you need help in a crowd, single someone out: “You, in the red jacket — call an ambulance.”',
      relatedConcepts: ['Bystander effect', 'Diffusion of responsibility', 'Pluralistic ignorance'],
      references: [
        { title: 'Bystander intervention in emergencies: Diffusion of responsibility', source: 'Journal of Personality and Social Psychology', year: 1968 },
      ],
      dateAdded: '2024-04-01',
    },
    {
      id: 'soc-2',
      collectionId: 'social-influence',
      number: 2,
      title: 'People will deny clear evidence to match a group.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'In Asch’s conformity experiments, a substantial share of participants gave an obviously wrong answer to match the unanimous group.',
      whyItHappens: 'Belonging is a deep need, and social consensus is a shortcut for what is true. Disagreeing with everyone feels costly.',
      realWorldExample: 'In a meeting where everyone nods at a flawed plan, silence can look like agreement and the error goes unchallenged.',
      practicalUse: 'Appoint a genuine dissenter or invite the objection first — a single ally sharply reduces conformity.',
      relatedConcepts: ['Conformity', 'Asch effect', 'Social proof'],
      references: [
        { title: 'Effects of group pressure upon the modification and distortion of judgments', source: 'Groups, Leadership and Men', year: 1951 },
      ],
      dateAdded: '2024-04-02',
    },
    {
      id: 'soc-3',
      collectionId: 'social-influence',
      number: 3,
      title: 'Ordinary people will follow authority even against their conscience.',
      readingTimeMinutes: 4,
      evidenceLevel: 5,
      summary: 'In Milgram’s obedience studies, many participants continued administering what they believed were painful shocks because an authority figure told them to.',
      whyItHappens: 'People shift into an “agentic” state, feeling responsible to the authority rather than for their own actions, especially when the authority appears legitimate.',
      realWorldExample: 'The pattern echoes through history, where ordinary people carried out harmful orders while feeling they were merely following procedure.',
      practicalUse: 'When instructed to do something that feels wrong, pause and name who is accountable for the outcome — that reframing restores personal agency.',
      relatedConcepts: ['Obedience to authority', 'Agentic state', 'Moral disengagement'],
      references: [
        { title: 'Behavioral Study of Obedience', source: 'Journal of Abnormal and Social Psychology', year: 1963 },
      ],
      dateAdded: '2024-04-03',
    },
    {
      id: 'soc-4',
      collectionId: 'social-influence',
      number: 4,
      title: 'Cohesive groups can talk themselves into bad decisions.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Groupthink is a mode of thinking in highly cohesive groups where the desire for harmony suppresses dissent and realistic appraisal of alternatives.',
      whyItHappens: 'Pressure to agree, self-censorship and an illusion of unanimity combine so that doubts are never voiced and warnings are ignored.',
      realWorldExample: 'Several well-documented policy disasters have been attributed to teams that insulated themselves from dissenting views.',
      practicalUse: 'Build in a devil’s advocate, invite outside perspectives, and have leaders withhold their opinion until others have spoken.',
      relatedConcepts: ['Groupthink', 'Group polarisation', 'Illusion of unanimity'],
      references: [
        { title: 'Victims of Groupthink', source: 'Houghton Mifflin', year: 1972 },
      ],
      dateAdded: '2024-04-04',
    },
  ],
};
