import { FactCollection } from '../../types';

export const cognitiveBiases: FactCollection = {
  id: 'cognitive-biases',
  categoryId: 'psychology',
  title: 'Cognitive Biases',
  description: 'Mental shortcuts and errors.',
  icon: 'split-square-horizontal',
  colorClass: 'text-cyan-500',
  facts: [
    {
      id: 'bias-1',
      collectionId: 'cognitive-biases',
      number: 1,
      title: 'The least skilled tend to overestimate their ability most.',
      readingTimeMinutes: 4,
      evidenceLevel: 4,
      summary: 'The Dunning–Kruger effect describes how people with low ability in a domain often overestimate their competence, while experts tend to underestimate theirs.',
      whyItHappens: 'The skills needed to perform well are often the same skills needed to recognise good performance. Without them, a person cannot see their own errors or others’ expertise.',
      realWorldExample: 'In classic studies, participants scoring in the bottom quartile on tests of logic and grammar rated their own performance far higher than it was.',
      practicalUse: 'Treat confidence in a domain you have barely studied as a warning, and calibrate your self-assessment against feedback and external benchmarks.',
      relatedConcepts: ['Dunning–Kruger effect', 'Illusory superiority', 'Metacognition'],
      references: [
        { title: 'Unskilled and Unaware of It', source: 'Journal of Personality and Social Psychology', year: 1999 },
      ],
      dateAdded: '2024-02-10',
    },
    {
      id: 'bias-2',
      collectionId: 'cognitive-biases',
      number: 2,
      title: 'We seek out information that confirms what we already believe.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'Confirmation bias is the tendency to search for, interpret and remember information in a way that supports existing beliefs.',
      whyItHappens: 'Holding consistent beliefs feels comfortable, and processing supportive information is cognitively cheaper than confronting contradiction.',
      realWorldExample: 'Two people reading the same balanced article can each come away convinced it supports their opposing views.',
      practicalUse: 'Actively ask what evidence would prove you wrong, and seek out the strongest version of the opposing case before deciding.',
      relatedConcepts: ['Confirmation bias', 'Belief bias', 'Motivated reasoning'],
      references: [
        { title: 'The case for motivated reasoning', source: 'Psychological Bulletin', year: 1990 },
      ],
      dateAdded: '2024-02-11',
    },
    {
      id: 'bias-3',
      collectionId: 'cognitive-biases',
      number: 3,
      title: 'Once we know the outcome, we feel we knew it all along.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'Hindsight bias is the tendency to see past events as having been more predictable than they actually were before they occurred.',
      whyItHappens: 'After an event, new knowledge is blended into memory, so the uncertainty that existed beforehand is quietly erased.',
      realWorldExample: 'After a market crash or an election result, commentators “always” saw it coming — a claim rarely made with the same confidence in advance.',
      practicalUse: 'Write down predictions and reasoning before an outcome is known, so you can check your calibration honestly afterwards.',
      relatedConcepts: ['Hindsight bias', 'Outcome bias', 'Overconfidence'],
      references: [
        { title: 'Hindsight ≠ Foresight: The Effect of Outcome Knowledge on Judgment Under Uncertainty', source: 'Journal of Experimental Psychology: Human Perception and Performance', year: 1975 },
      ],
      dateAdded: '2024-02-12',
    },
    {
      id: 'bias-4',
      collectionId: 'cognitive-biases',
      number: 4,
      title: 'Vivid events feel far more likely than they really are.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'The availability heuristic is the tendency to judge the probability of an event by how easily examples come to mind.',
      whyItHappens: 'The mind estimates frequency from the ease of recall. Dramatic, recent or widely reported events are easier to recall, so they feel more common than they are.',
      realWorldExample: 'Highly publicised plane crashes make flying feel more dangerous than driving, even though driving carries the greater statistical risk.',
      practicalUse: 'When estimating risk, look up the actual base rates rather than trusting whatever comes to mind most easily.',
      relatedConcepts: ['Availability heuristic', 'Risk perception', 'Negativity bias'],
      references: [
        { title: 'Judgment under Uncertainty: Heuristics and Biases', source: 'Science', year: 1974 },
      ],
      dateAdded: '2024-02-13',
    },
    {
      id: 'bias-5',
      collectionId: 'cognitive-biases',
      number: 5,
      title: 'One good trait makes us assume a person has many others.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'The halo effect is the tendency for a positive impression in one area to spill over into unrelated judgments about a person or brand.',
      whyItHappens: 'Impressions are formed globally and quickly; the mind fills in gaps by assuming traits cluster together, rather than evaluating each independently.',
      realWorldExample: 'Attractive or well-spoken candidates are often rated as more competent and honest, unrelated to the actual job demands.',
      practicalUse: 'In hiring or appraisal, separate the dimensions you are judging and score them independently before forming an overall view.',
      relatedConcepts: ['Halo effect', 'First impressions', 'Fundamental attribution error'],
      references: [
        { title: 'A Constant Error in Psychological Ratings', source: 'Journal of Applied Psychology', year: 1920 },
      ],
      dateAdded: '2024-02-14',
    },
  ],
};
