import { FactCollection } from '../../types';

export const decisionMaking: FactCollection = {
  id: 'decision-making',
  categoryId: 'psychology',
  title: 'Decision Making',
  description: 'Choices, judgment and risk.',
  icon: 'git-branch',
  colorClass: 'text-emerald-500',
  facts: [
    {
      id: 'decision-1',
      collectionId: 'decision-making',
      number: 1,
      title: 'We keep investing in lost causes because of what we have already spent.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'The sunk cost fallacy is the tendency to continue a course of action simply because of resources already invested — money, time or effort — even when quitting would be more rational.',
      whyItHappens: 'People dislike waste and want to appear consistent. Persisting feels like protecting the earlier investment, so the past cost is treated as a reason to continue rather than as irrelevant to the next decision.',
      realWorldExample: 'You sit through a bad film because you paid for the ticket, or keep pouring money into a failing project because of how much has already gone in.',
      practicalUse: 'Ask a simple question: “If I had not spent anything so far, would I start this today?” If the answer is no, the sunk cost is driving the decision.',
      relatedConcepts: ['Sunk cost fallacy', 'Loss aversion', 'Escalation of commitment'],
      references: [
        { title: 'The Psychology of Sunk Cost', source: 'Organizational Behavior and Human Decision Processes', year: 1985 },
      ],
      dateAdded: '2024-02-01',
    },
    {
      id: 'decision-2',
      collectionId: 'decision-making',
      number: 2,
      title: 'Too many options can make choosing harder and less satisfying.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Choice overload describes how an abundance of options increases cognitive effort, can reduce the likelihood of choosing at all, and lowers satisfaction with whatever is finally chosen.',
      whyItHappens: 'Evaluating many alternatives consumes working memory and invites regret about the options not taken. The mind trades a good-enough choice for the cost of endless comparison.',
      realWorldExample: 'A famous field study found shoppers were far more likely to buy jam when offered six varieties than when offered twenty-four.',
      practicalUse: 'Deliberately limit the set you choose from. Shortlists of three to five options beat open-ended “all possibilities”.',
      relatedConcepts: ['Choice overload', 'Decision fatigue', 'Maximiser vs. satisficer'],
      references: [
        { title: 'When Choice is Demotivating', source: 'Journal of Personality and Social Psychology', year: 2000 },
      ],
      dateAdded: '2024-02-02',
    },
    {
      id: 'decision-3',
      collectionId: 'decision-making',
      number: 3,
      title: 'An arbitrary number can pull your estimate toward it.',
      readingTimeMinutes: 3,
      evidenceLevel: 5,
      summary: 'Anchoring is the tendency for an initial value — even an irrelevant one — to bias subsequent numerical judgments in its direction.',
      whyItHappens: 'When uncertain, the mind uses the first available number as a starting point and adjusts from there, but the adjustment is usually insufficient.',
      realWorldExample: 'Participants who spun a wheel of fortune landing on a high number later gave higher estimates of how many African countries were in the UN.',
      practicalUse: 'In any negotiation or estimate, set your own anchor first, and treat the other side’s opening figure as information to be evaluated — not a reference point to adjust from.',
      relatedConcepts: ['Anchoring', 'Adjustment heuristic', 'Negotiation'],
      references: [
        { title: 'Judgment under Uncertainty: Heuristics and Biases', source: 'Science', year: 1974 },
      ],
      dateAdded: '2024-02-03',
    },
    {
      id: 'decision-4',
      collectionId: 'decision-making',
      number: 4,
      title: 'Making many decisions wears down self-control.',
      readingTimeMinutes: 3,
      evidenceLevel: 3,
      summary: 'Repeated decision-making depletes the mental resources available for self-control, making later choices more impulsive or prone to defaulting.',
      whyItHappens: 'Deciding is effortful and competes for limited executive resources. As those resources are spent, people default to the easier option or avoid choosing at all.',
      realWorldExample: 'Endless small decisions during a day — what to eat, what to reply — can leave you with little resolve for a difficult choice in the evening.',
      practicalUse: 'Automate or schedule routine decisions (meals, outfits, a fixed work order) so your best judgment is reserved for the choices that matter.',
      relatedConcepts: ['Ego depletion', 'Decision fatigue', 'Status quo bias'],
      references: [
        { title: 'Extraneous factors in judicial decisions', source: 'PNAS', year: 2011 },
      ],
      dateAdded: '2024-02-04',
    },
    {
      id: 'decision-5',
      collectionId: 'decision-making',
      number: 5,
      title: 'We judge a decision by its outcome, not by the quality of the choice.',
      readingTimeMinutes: 3,
      evidenceLevel: 4,
      summary: 'Outcome bias is the tendency to evaluate a decision by how things turned out rather than by what was known and reasonable at the time it was made.',
      whyItHappens: 'Hindsight makes outcomes feel inevitable, so good decisions that turned out badly are judged harshly and reckless decisions that happened to work are praised.',
      realWorldExample: 'A doctor is blamed for a rare complication that no reasonable test could have predicted, while a gambler who wins is treated as shrewd.',
      practicalUse: 'Judge decisions by the process and the information available, not just the result — and apply the same standard to yourself.',
      relatedConcepts: ['Outcome bias', 'Hindsight bias', 'Resulting'],
      references: [
        { title: 'Outcome bias in decision evaluation', source: 'Journal of Personality and Social Psychology', year: 1988 },
      ],
      dateAdded: '2024-02-05',
    },
  ],
};
